#!/usr/bin/env bash
# This script tells the story of /etc/passwd users based on specific fields.

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY COMMAND_SHELL; do
    # 'USER ID INFO' sahəsini əldə etmək üçün:
    # Eğer USER_INFO boşsa, USERNAME-i istifadə et (nümunədə bəzi yerlərdə belədir)
    # Nümunə çıxışa əsasən bəzən USER_INFO boş olduqda USERNAME-i göstərir,
    # bəzən isə boş qalır.
    # Ən yaxşı yanaşma: USER_INFO boş deyilsə onu, boşdursa USERNAME-i istifadə et.
    # Lakin nümunə çıxışdakı "more info about the user here: " hissəsi boş olduqda
    # həqiqətən də boş qalır. Bu zaman USER_INFO dəyişkənini olduğu kimi istifadə edək,
    # boşluqları və vergülləri nəzərə alaraq.

    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" \
        "$USERNAME" "$GROUP_ID" "$HOME_DIRECTORY" "$COMMAND_SHELL" "$USER_ID" "$PASSWORD" "$USER_INFO"
done < /etc/passwd
