#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from Apache logs and displays sorted data.

awk '{counts[$1 " " $9]++} END {for (key in counts) printf "%7d %s\n", counts[key], key}' apache-access.log | sort -rn
